start: statements+

?statements: function+
           | assignment+

function: "fn" identifier "{" block "}"

identifier: CNAME

block: statements+

expression: expression operator expression
          | "(" expression ")"
          | identifier
          | NUMBER

operator: "+" -> add
        | "-" -> sub
        | "*" -> mul
        | "/" -> div

assignment: "let" identifier "=" expression

%import common.CNAME
%import common.NUMBER
%import common.WS
%ignore WS
